CREATE TABLE IF NOT EXISTS otp_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  code VARCHAR(10) NOT NULL,
  expiresAt TIMESTAMP NOT NULL,
  used TINYINT NOT NULL DEFAULT 0,
  attempts INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
