-- Batch 3: 50 additional exam questions for Module 5 (§34i Darlehensvermittlung)
-- Total questions after this batch: 200
-- Distribution: Rechtliche Grundlagen (10), Darlehensarten (10), Finanzierungsplanung (10), Bonitätsprüfung (7), Risiken (7), Verbraucherschutz (6)

INSERT INTO question_bank (moduleId, category, difficulty, questionText, options, correctAnswer, explanation) VALUES

-- Rechtliche Grundlagen (10 Fragen, ID 151-160)
(5, 'Rechtliche Grundlagen', 'easy', 'Welche Behörde ist für die Erlaubniserteilung nach §34i GewO zuständig?', '["Industrie- und Handelskammer (IHK)", "Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin)", "Gewerbeaufsichtsamt", "Bundeskartellamt"]', 'Industrie- und Handelskammer (IHK)', 'Die IHK ist für die Erlaubniserteilung nach §34i GewO zuständig, nicht die BaFin (die nur für Finanzdienstleistungsinstitute zuständig ist).'),

(5, 'Rechtliche Grundlagen', 'medium', 'Ein Darlehensvermittler verletzt seine Beratungspflichten. Welche Rechtsfolge droht?', '["Bußgeld bis 50.000 EUR, Schadensersatz, Erlaubnisentzug", "Nur Bußgeld", "Nur Schadensersatz", "Nur Erlaubnisentzug"]', 'Bußgeld bis 50.000 EUR, Schadensersatz, Erlaubnisentzug', 'Bei Verletzung der Beratungspflichten drohen Bußgeld (bis 50.000 EUR nach §144 GewO), Schadensersatz (§280 BGB) und Erlaubnisentzug (§35 GewO).'),

(5, 'Rechtliche Grundlagen', 'hard', 'Was ist der Unterschied zwischen §34c und §34i GewO?', '["§34c regelt Immobilienmakler, §34i regelt Darlehensvermittler", "§34c regelt Darlehensvermittler, §34i regelt Immobilienmakler", "Kein Unterschied", "§34c ist für Gewerbe, §34i für Privatpersonen"]', '§34c regelt Immobilienmakler, §34i regelt Darlehensvermittler', '§34c GewO regelt die Erlaubnispflicht für Immobilienmakler und Wohnimmobilienverwalter, §34i GewO regelt die Erlaubnispflicht für Darlehensvermittler.'),

(5, 'Rechtliche Grundlagen', 'easy', 'Welche Versicherung muss ein Darlehensvermittler nach §34i GewO abschließen?', '["Berufshaftpflichtversicherung", "Rechtsschutzversicherung", "Unfallversicherung", "Lebensversicherung"]', 'Berufshaftpflichtversicherung', 'Nach §34i Abs. 2 Nr. 3 GewO muss ein Darlehensvermittler eine Berufshaftpflichtversicherung mit Mindestdeckungssummen abschließen.'),

(5, 'Rechtliche Grundlagen', 'medium', 'Wie hoch ist die Mindestdeckungssumme der Berufshaftpflichtversicherung nach §34i GewO?', '["1,26 Mio. EUR pro Schadensfall", "500.000 EUR pro Schadensfall", "2 Mio. EUR pro Schadensfall", "250.000 EUR pro Schadensfall"]', '1,26 Mio. EUR pro Schadensfall', 'Die Mindestdeckungssumme beträgt 1,26 Mio. EUR pro Schadensfall nach § 2 Abs. 1 DarlVermV.'),

(5, 'Rechtliche Grundlagen', 'hard', 'Was ist der Unterschied zwischen Darlehensvermittler und Darlehensgeber?', '["Darlehensvermittler vermittelt Darlehen, Darlehensgeber vergibt Darlehen", "Darlehensvermittler vergibt Darlehen, Darlehensgeber vermittelt Darlehen", "Kein Unterschied", "Darlehensvermittler ist immer eine Bank"]', 'Darlehensvermittler vermittelt Darlehen, Darlehensgeber vergibt Darlehen', 'Der Darlehensvermittler vermittelt nur Darlehen zwischen Darlehensnehmer und Darlehensgeber (Bank), vergibt aber selbst keine Darlehen.'),

(5, 'Rechtliche Grundlagen', 'easy', 'Welche Eintragung muss ein Darlehensvermittler vornehmen?', '["Eintragung im Vermittlerregister (§34i GewO)", "Eintragung im Handelsregister", "Eintragung im Grundbuch", "Eintragung im Vereinsregister"]', 'Eintragung im Vermittlerregister (§34i GewO)', 'Nach §34i Abs. 1 GewO muss ein Darlehensvermittler im Vermittlerregister eingetragen sein.'),

(5, 'Rechtliche Grundlagen', 'medium', 'Ein Darlehensvermittler erhält eine Provision von 5% des Darlehensbetrags. Ist das zulässig?', '["Ja, wenn vorher transparent offengelegt", "Nein, Provision ist generell verboten", "Ja, ohne Offenlegung", "Nur bei Darlehen über 100.000 EUR"]', 'Ja, wenn vorher transparent offengelegt', 'Die Provision ist zulässig, wenn sie vorher transparent offengelegt wird (§ 34i Abs. 5 GewO, Art. 247 § 13 EGBGB).'),

(5, 'Rechtliche Grundlagen', 'hard', 'Was ist die Immobiliarkreditrichtlinie (IKR)?', '["EU-Richtlinie zum Schutz von Verbrauchern bei Immobilienkrediten", "Deutsches Gesetz für Immobilienmakler", "Verordnung für Grundbucheintragungen", "Richtlinie für Baufinanzierung"]', 'EU-Richtlinie zum Schutz von Verbrauchern bei Immobilienkrediten', 'Die Immobiliarkreditrichtlinie (Richtlinie 2014/17/EU) ist eine EU-Richtlinie zum Schutz von Verbrauchern bei Immobilienkrediten, umgesetzt in Deutschland durch §§ 491ff. BGB.'),

(5, 'Rechtliche Grundlagen', 'easy', 'Welche Sachkundeprüfung muss ein Darlehensvermittler ablegen?', '["IHK-Sachkundeprüfung nach §34i GewO", "Steuerberaterprüfung", "Immobilienmaklerprüfung", "Keine Prüfung erforderlich"]', 'IHK-Sachkundeprüfung nach §34i GewO', 'Nach §34i Abs. 1 Nr. 1 GewO muss ein Darlehensvermittler eine IHK-Sachkundeprüfung ablegen.'),

-- Darlehensarten (10 Fragen, ID 161-170)
(5, 'Darlehensarten', 'easy', 'Was ist ein Bauspardarlehen?', '["Darlehen zur Finanzierung von Wohneigentum nach Ansparphase", "Darlehen für Unternehmen", "Darlehen für Konsumgüter", "Darlehen für Studium"]', 'Darlehen zur Finanzierung von Wohneigentum nach Ansparphase', 'Ein Bauspardarlehen ist ein Darlehen zur Finanzierung von Wohneigentum, das nach einer Ansparphase bei einer Bausparkasse gewährt wird.'),

(5, 'Darlehensarten', 'medium', 'Ein Kunde möchte ein Bauspardarlehen aufnehmen. Welche Voraussetzung muss erfüllt sein?', '["Mindestguthaben erreicht, Zuteilungsreife", "Nur Mindestguthaben", "Nur Zuteilungsreife", "Keine Voraussetzungen"]', 'Mindestguthaben erreicht, Zuteilungsreife', 'Für ein Bauspardarlehen muss das Mindestguthaben erreicht sein und die Zuteilungsreife vorliegen.'),

(5, 'Darlehensarten', 'hard', 'Was ist der Unterschied zwischen Annuitätendarlehen und endfälligem Darlehen?', '["Annuitätendarlehen: konstante Rate mit Tilgung, Endfälliges: nur Zinsen, Tilgung am Ende", "Annuitätendarlehen: nur Zinsen, Endfälliges: konstante Rate", "Kein Unterschied", "Annuitätendarlehen ist teurer"]', 'Annuitätendarlehen: konstante Rate mit Tilgung, Endfälliges: nur Zinsen, Tilgung am Ende', 'Beim Annuitätendarlehen wird eine konstante Rate (Zinsen + Tilgung) gezahlt, beim endfälligen Darlehen werden nur Zinsen gezahlt und die Tilgung erfolgt am Ende der Laufzeit.'),

(5, 'Darlehensarten', 'easy', 'Was ist ein KfW-Darlehen?', '["Förderkredit der Kreditanstalt für Wiederaufbau", "Privatkredit einer Bank", "Darlehen für Unternehmen", "Darlehen für Studium"]', 'Förderkredit der Kreditanstalt für Wiederaufbau', 'Ein KfW-Darlehen ist ein Förderkredit der Kreditanstalt für Wiederaufbau (KfW) mit günstigen Konditionen für energieeffizientes Bauen, Sanieren oder Kaufen.'),

(5, 'Darlehensarten', 'medium', 'Ein Kunde möchte ein KfW-Darlehen für energieeffizientes Bauen aufnehmen. Welche KfW-Effizienzhaus-Stufe ist am günstigsten?', '["KfW 40 Plus (höchste Förderung)", "KfW 55", "KfW 70", "KfW 85"]', 'KfW 40 Plus (höchste Förderung)', 'KfW 40 Plus ist die höchste Effizienzhaus-Stufe und erhält die höchste Förderung (niedrigste Zinsen, höchster Tilgungszuschuss).'),

(5, 'Darlehensarten', 'hard', 'Was ist ein Cap-Darlehen?', '["Variables Darlehen mit Zinsobergrenze", "Darlehen mit fester Zinsbindung", "Darlehen ohne Zinsen", "Darlehen mit Tilgungsaussetzung"]', 'Variables Darlehen mit Zinsobergrenze', 'Ein Cap-Darlehen ist ein variables Darlehen, bei dem der Zinssatz an den Marktzins gekoppelt ist, aber eine Obergrenze (Cap) hat.'),

(5, 'Darlehensarten', 'easy', 'Was ist ein Forward-Darlehen?', '["Darlehen, das heute vereinbart und später ausgezahlt wird", "Darlehen, das sofort ausgezahlt wird", "Darlehen ohne Zinsen", "Darlehen für Unternehmen"]', 'Darlehen, das heute vereinbart und später ausgezahlt wird', 'Ein Forward-Darlehen ist ein Darlehen, das heute zu festen Konditionen vereinbart wird, aber erst in der Zukunft (z.B. nach Ablauf der Zinsbindung) ausgezahlt wird.'),

(5, 'Darlehensarten', 'medium', 'Ein Kunde möchte ein Forward-Darlehen für eine Anschlussfinanzierung in 2 Jahren abschließen. Welcher Aufschlag ist üblich?', '["0,01-0,03% pro Monat Vorlaufzeit", "Kein Aufschlag", "0,1% pro Monat", "0,5% pro Monat"]', '0,01-0,03% pro Monat Vorlaufzeit', 'Für Forward-Darlehen wird üblicherweise ein Aufschlag von 0,01-0,03% pro Monat Vorlaufzeit berechnet.'),

(5, 'Darlehensarten', 'hard', 'Was ist ein Volltilgerdarlehen?', '["Darlehen, das am Ende der Zinsbindung vollständig getilgt ist", "Darlehen ohne Tilgung", "Darlehen mit variabler Tilgung", "Darlehen mit Sondertilgung"]', 'Darlehen, das am Ende der Zinsbindung vollständig getilgt ist', 'Ein Volltilgerdarlehen ist ein Darlehen, bei dem die Tilgung so hoch ist, dass das Darlehen am Ende der Zinsbindung vollständig getilgt ist (Restschuld = 0 EUR).'),

(5, 'Darlehensarten', 'easy', 'Was ist ein Konstantdarlehen?', '["Darlehen mit konstanter monatlicher Rate (Annuitätendarlehen)", "Darlehen mit variabler Rate", "Darlehen ohne Rate", "Darlehen mit Tilgungsaussetzung"]', 'Darlehen mit konstanter monatlicher Rate (Annuitätendarlehen)', 'Ein Konstantdarlehen ist ein anderer Begriff für ein Annuitätendarlehen, bei dem die monatliche Rate konstant bleibt.'),

-- Finanzierungsplanung (10 Fragen, ID 171-180)
(5, 'Finanzierungsplanung', 'easy', 'Was ist eine Anschlussfinanzierung?', '["Neue Finanzierung nach Ablauf der Zinsbindung", "Erste Finanzierung beim Kauf", "Finanzierung für Renovierung", "Finanzierung für Nebenkosten"]', 'Neue Finanzierung nach Ablauf der Zinsbindung', 'Eine Anschlussfinanzierung ist eine neue Finanzierung, die nach Ablauf der Zinsbindung des ursprünglichen Darlehens abgeschlossen wird.'),

(5, 'Finanzierungsplanung', 'medium', 'Ein Kunde hat nach 10 Jahren Zinsbindung noch 150.000 EUR Restschuld. Welche Optionen hat er für die Anschlussfinanzierung?', '["Prolongation, Umschuldung, Forward-Darlehen", "Nur Prolongation", "Nur Umschuldung", "Nur Forward-Darlehen"]', 'Prolongation, Umschuldung, Forward-Darlehen', 'Der Kunde kann eine Prolongation (Verlängerung bei der gleichen Bank), eine Umschuldung (Wechsel zu einer anderen Bank) oder ein Forward-Darlehen (frühzeitige Vereinbarung) wählen.'),

(5, 'Finanzierungsplanung', 'hard', 'Was ist der Unterschied zwischen Prolongation und Umschuldung?', '["Prolongation: gleiche Bank, Umschuldung: andere Bank", "Prolongation: andere Bank, Umschuldung: gleiche Bank", "Kein Unterschied", "Prolongation ist teurer"]', 'Prolongation: gleiche Bank, Umschuldung: andere Bank', 'Bei einer Prolongation bleibt der Kunde bei der gleichen Bank und verlängert das Darlehen, bei einer Umschuldung wechselt er zu einer anderen Bank.'),

(5, 'Finanzierungsplanung', 'easy', 'Was ist eine Umschuldung?', '["Wechsel zu einer anderen Bank für bessere Konditionen", "Verlängerung bei der gleichen Bank", "Tilgung des Darlehens", "Erhöhung des Darlehens"]', 'Wechsel zu einer anderen Bank für bessere Konditionen', 'Eine Umschuldung ist der Wechsel zu einer anderen Bank, um bessere Konditionen (z.B. niedrigere Zinsen) zu erhalten.'),

(5, 'Finanzierungsplanung', 'medium', 'Ein Kunde möchte umschulden. Welche Kosten können anfallen?', '["Vorfälligkeitsentschädigung, Grundbuchkosten, Notarkosten", "Nur Vorfälligkeitsentschädigung", "Nur Grundbuchkosten", "Keine Kosten"]', 'Vorfälligkeitsentschädigung, Grundbuchkosten, Notarkosten', 'Bei einer Umschuldung können Vorfälligkeitsentschädigung (bei vorzeitiger Ablösung), Grundbuchkosten (Abtretung der Grundschuld) und Notarkosten anfallen.'),

(5, 'Finanzierungsplanung', 'hard', 'Was ist eine Abtretung der Grundschuld?', '["Übertragung der Grundschuld von einer Bank zur anderen", "Löschung der Grundschuld", "Eintragung einer neuen Grundschuld", "Erhöhung der Grundschuld"]', 'Übertragung der Grundschuld von einer Bank zur anderen', 'Eine Abtretung der Grundschuld ist die Übertragung der Grundschuld von der alten Bank zur neuen Bank bei einer Umschuldung.'),

(5, 'Finanzierungsplanung', 'easy', 'Was ist eine Prolongation?', '["Verlängerung des Darlehens bei der gleichen Bank", "Wechsel zu einer anderen Bank", "Tilgung des Darlehens", "Erhöhung des Darlehens"]', 'Verlängerung des Darlehens bei der gleichen Bank', 'Eine Prolongation ist die Verlängerung des Darlehens bei der gleichen Bank nach Ablauf der Zinsbindung.'),

(5, 'Finanzierungsplanung', 'medium', 'Ein Kunde erhält ein Prolongationsangebot mit 3,5% Zinssatz. Der Marktzins liegt bei 2,8%. Was sollte er tun?', '["Umschuldung prüfen, bessere Konditionen bei anderer Bank", "Prolongation akzeptieren", "Darlehen sofort tilgen", "Nichts tun"]', 'Umschuldung prüfen, bessere Konditionen bei anderer Bank', 'Wenn das Prolongationsangebot deutlich über dem Marktzins liegt, sollte der Kunde eine Umschuldung zu einer anderen Bank mit besseren Konditionen prüfen.'),

(5, 'Finanzierungsplanung', 'hard', 'Was ist eine Anschlussfinanzierung mit Sondertilgung?', '["Anschlussfinanzierung mit Option zur außerplanmäßigen Tilgung", "Anschlussfinanzierung ohne Tilgung", "Anschlussfinanzierung mit variabler Tilgung", "Anschlussfinanzierung mit Tilgungsaussetzung"]', 'Anschlussfinanzierung mit Option zur außerplanmäßigen Tilgung', 'Eine Anschlussfinanzierung mit Sondertilgung ermöglicht außerplanmäßige Tilgungen zusätzlich zur regulären Rate, um das Darlehen schneller zurückzuzahlen.'),

(5, 'Finanzierungsplanung', 'easy', 'Was ist eine Restschuld?', '["Verbleibender Darlehensbetrag nach Ablauf der Zinsbindung", "Gesamter Darlehensbetrag", "Tilgungsbetrag", "Zinsbetrag"]', 'Verbleibender Darlehensbetrag nach Ablauf der Zinsbindung', 'Die Restschuld ist der verbleibende Darlehensbetrag, der nach Ablauf der Zinsbindung noch nicht getilgt ist.'),

-- Bonitätsprüfung (7 Fragen, ID 181-187)
(5, 'Bonitätsprüfung', 'easy', 'Welche Rolle spielt die Schufa bei der Kreditvergabe?', '["Bewertung der Kreditwürdigkeit des Kunden", "Vergabe des Kredits", "Berechnung der Zinsen", "Eintragung im Grundbuch"]', 'Bewertung der Kreditwürdigkeit des Kunden', 'Die Schufa bewertet die Kreditwürdigkeit des Kunden anhand von Daten über Zahlungsverhalten, Kredithistorie und offene Kredite.'),

(5, 'Bonitätsprüfung', 'medium', 'Ein Kunde hat einen Schufa-Score von 95%. Wie ist seine Bonität einzuschätzen?', '["Sehr gute Bonität", "Mittlere Bonität", "Schlechte Bonität", "Keine Bonität"]', 'Sehr gute Bonität', 'Ein Schufa-Score von 95% bedeutet sehr gute Bonität (95-100% = sehr geringes Ausfallrisiko).'),

(5, 'Bonitätsprüfung', 'hard', 'Was ist der Unterschied zwischen Schufa-Auskunft und Schufa-Score?', '["Schufa-Auskunft: detaillierte Informationen, Schufa-Score: Kennzahl (0-100%)", "Schufa-Auskunft: Kennzahl, Schufa-Score: detaillierte Informationen", "Kein Unterschied", "Schufa-Auskunft ist kostenlos, Schufa-Score kostenpflichtig"]', 'Schufa-Auskunft: detaillierte Informationen, Schufa-Score: Kennzahl (0-100%)', 'Die Schufa-Auskunft enthält detaillierte Informationen über Kredithistorie, Zahlungsverhalten und offene Kredite, der Schufa-Score ist eine Kennzahl (0-100%) für die Kreditwürdigkeit.'),

(5, 'Bonitätsprüfung', 'easy', 'Welche Unterlagen benötigt eine Bank für die Bonitätsprüfung bei Selbstständigen?', '["Einkommenssteuerbescheide, BWA, Bilanzen", "Nur Einkommenssteuerbescheide", "Nur BWA", "Nur Bilanzen"]', 'Einkommenssteuerbescheide, BWA, Bilanzen', 'Für Selbstständige benötigt die Bank Einkommenssteuerbescheide der letzten 2-3 Jahre, betriebswirtschaftliche Auswertungen (BWA) und Bilanzen.'),

(5, 'Bonitätsprüfung', 'medium', 'Ein selbstständiger Kunde hat schwankende Einkommen. Wie wird die Bonität bewertet?', '["Durchschnitt der letzten 2-3 Jahre", "Nur letztes Jahr", "Nur bestes Jahr", "Nur schlechtestes Jahr"]', 'Durchschnitt der letzten 2-3 Jahre', 'Bei schwankenden Einkommen wird der Durchschnitt der letzten 2-3 Jahre herangezogen, um die Bonität zu bewerten.'),

(5, 'Bonitätsprüfung', 'hard', 'Was ist eine Selbstauskunft des Kunden?', '["Formular mit Angaben zu Einkommen, Vermögen, Verbindlichkeiten", "Schufa-Auskunft", "Einkommenssteuerbescheid", "Arbeitsvertrag"]', 'Formular mit Angaben zu Einkommen, Vermögen, Verbindlichkeiten', 'Eine Selbstauskunft ist ein Formular, in dem der Kunde Angaben zu Einkommen, Vermögen, Verbindlichkeiten und anderen finanziellen Verhältnissen macht.'),

(5, 'Bonitätsprüfung', 'easy', 'Welche Bedeutung hat das Eigenkapital für die Bonität?', '["Höheres Eigenkapital = bessere Bonität, niedrigere Zinsen", "Eigenkapital hat keine Bedeutung", "Höheres Eigenkapital = schlechtere Bonität", "Eigenkapital ist nur für Unternehmen relevant"]', 'Höheres Eigenkapital = bessere Bonität, niedrigere Zinsen', 'Höheres Eigenkapital verbessert die Bonität, da das Ausfallrisiko für die Bank sinkt, und führt zu niedrigeren Zinsen.'),

-- Risiken (7 Fragen, ID 188-194)
(5, 'Risiken', 'easy', 'Was ist ein Arbeitslosigkeitsrisiko?', '["Risiko, dass der Darlehensnehmer arbeitslos wird und die Rate nicht zahlen kann", "Risiko steigender Zinsen", "Risiko sinkender Immobilienpreise", "Risiko steigender Nebenkosten"]', 'Risiko, dass der Darlehensnehmer arbeitslos wird und die Rate nicht zahlen kann', 'Das Arbeitslosigkeitsrisiko ist das Risiko, dass der Darlehensnehmer arbeitslos wird und die monatliche Rate nicht mehr zahlen kann.'),

(5, 'Risiken', 'medium', 'Ein Kunde möchte sich gegen Arbeitslosigkeit absichern. Welche Versicherung ist geeignet?', '["Restschuldversicherung mit Arbeitslosigkeitsschutz", "Rechtsschutzversicherung", "Unfallversicherung", "Lebensversicherung"]', 'Restschuldversicherung mit Arbeitslosigkeitsschutz', 'Eine Restschuldversicherung mit Arbeitslosigkeitsschutz übernimmt die Raten bei Arbeitslosigkeit des Darlehensnehmers.'),

(5, 'Risiken', 'hard', 'Was ist ein Klumpenrisiko?', '["Konzentration des Vermögens auf eine Anlage (z.B. nur Immobilie)", "Risiko steigender Zinsen", "Risiko sinkender Immobilienpreise", "Risiko steigender Nebenkosten"]', 'Konzentration des Vermögens auf eine Anlage (z.B. nur Immobilie)', 'Das Klumpenrisiko ist das Risiko, dass das gesamte Vermögen auf eine Anlage (z.B. nur Immobilie) konzentriert ist und bei Wertverlust hohe Verluste entstehen.'),

(5, 'Risiken', 'easy', 'Was ist ein Zinsrisiko?', '["Risiko steigender Zinsen bei variabler Verzinsung oder Anschlussfinanzierung", "Risiko sinkender Immobilienpreise", "Risiko steigender Nebenkosten", "Risiko sinkender Einkommen"]', 'Risiko steigender Zinsen bei variabler Verzinsung oder Anschlussfinanzierung', 'Das Zinsrisiko ist das Risiko, dass die Zinsen bei variabler Verzinsung oder bei der Anschlussfinanzierung steigen und die monatliche Rate höher wird.'),

(5, 'Risiken', 'medium', 'Ein Kunde hat ein variables Darlehen mit 1,5% Zinssatz. Der Marktzins steigt auf 3,5%. Welches Risiko tritt ein?', '["Zinsrisiko: monatliche Rate steigt", "Tilgungsrisiko", "Währungsrisiko", "Kein Risiko"]', 'Zinsrisiko: monatliche Rate steigt', 'Bei einem variablen Darlehen steigt die monatliche Rate, wenn der Marktzins steigt (Zinsrisiko).'),

(5, 'Risiken', 'hard', 'Was ist ein Immobilienwertrisiko?', '["Risiko sinkender Immobilienpreise", "Risiko steigender Zinsen", "Risiko steigender Nebenkosten", "Risiko sinkender Einkommen"]', 'Risiko sinkender Immobilienpreise', 'Das Immobilienwertrisiko ist das Risiko, dass der Wert der Immobilie sinkt und bei einem Verkauf die Restschuld nicht gedeckt ist.'),

(5, 'Risiken', 'easy', 'Was ist eine Risikolebensversicherung?', '["Versicherung, die im Todesfall die Restschuld tilgt", "Versicherung gegen Arbeitslosigkeit", "Versicherung gegen Zinsänderungen", "Versicherung gegen Immobilienwertverfall"]', 'Versicherung, die im Todesfall die Restschuld tilgt', 'Eine Risikolebensversicherung tilgt im Todesfall des Darlehensnehmers die Restschuld, um die Hinterbliebenen zu schützen.'),

-- Verbraucherschutz (6 Fragen, ID 195-200)
(5, 'Verbraucherschutz', 'easy', 'Welche Informationen muss ein Darlehensvermittler vor Vertragsabschluss zur Verfügung stellen?', '["ESIS-Merkblatt, Provision, Widerrufsbelehrung", "Nur ESIS-Merkblatt", "Nur Provision", "Nur Widerrufsbelehrung"]', 'ESIS-Merkblatt, Provision, Widerrufsbelehrung', 'Nach § 34i Abs. 5 GewO und Art. 247 § 13 EGBGB muss ein Darlehensvermittler vor Vertragsabschluss das ESIS-Merkblatt, die Provision und die Widerrufsbelehrung in Textform zur Verfügung stellen.'),

(5, 'Verbraucherschutz', 'medium', 'Ein Kunde erhält kein ESIS-Merkblatt vor Vertragsabschluss. Welche Rechtsfolge tritt ein?', '["Verlängerung der Widerrufsfrist auf 1 Jahr und 14 Tage", "Keine Rechtsfolge", "Vertrag ist nichtig", "Nur Bußgeld"]', 'Verlängerung der Widerrufsfrist auf 1 Jahr und 14 Tage', 'Ohne ESIS-Merkblatt verlängert sich die Widerrufsfrist auf 1 Jahr und 14 Tage nach § 356 Abs. 3 BGB.'),

(5, 'Verbraucherschutz', 'hard', 'Was ist der Unterschied zwischen ESIS-Merkblatt und Widerrufsbelehrung?', '["ESIS: Darlehensinformationen, Widerrufsbelehrung: Widerrufsrecht", "ESIS: Widerrufsrecht, Widerrufsbelehrung: Darlehensinformationen", "Kein Unterschied", "ESIS ist für Unternehmen, Widerrufsbelehrung für Privatpersonen"]', 'ESIS: Darlehensinformationen, Widerrufsbelehrung: Widerrufsrecht', 'Das ESIS-Merkblatt enthält umfassende Darlehensinformationen (Zinssatz, Laufzeit, Kosten), die Widerrufsbelehrung informiert über das Widerrufsrecht (14 Tage).'),

(5, 'Verbraucherschutz', 'easy', 'Welche Frist gilt für das Widerrufsrecht bei Immobiliardarlehensverträgen?', '["14 Tage", "7 Tage", "21 Tage", "30 Tage"]', '14 Tage', 'Das Widerrufsrecht bei Immobiliardarlehensverträgen beträgt 14 Tage nach § 495 Abs. 1 BGB.'),

(5, 'Verbraucherschutz', 'medium', 'Ein Kunde widerruft einen Darlehensvertrag nach 12 Tagen. Welche Kosten muss er tragen?', '["Nur Zinsen für die Zeit bis zum Widerruf", "Vorfälligkeitsentschädigung", "Keine Kosten", "Schadensersatz"]', 'Nur Zinsen für die Zeit bis zum Widerruf', 'Bei Widerruf innerhalb der Widerrufsfrist muss der Kunde nur die Zinsen für die Zeit bis zum Widerruf zahlen (§ 357a BGB).'),

(5, 'Verbraucherschutz', 'hard', 'Was ist eine Beratungsdokumentation?', '["Protokoll über die Beratung des Kunden", "Schufa-Auskunft", "ESIS-Merkblatt", "Widerrufsbelehrung"]', 'Protokoll über die Beratung des Kunden', 'Eine Beratungsdokumentation ist ein Protokoll über die Beratung des Kunden, das die besprochenen Themen, Empfehlungen und Entscheidungen festhält (Pflicht nach § 511 BGB).');
