import { getDb } from "./db";
import { questionBank } from "../drizzle/schema";
import { sql } from "drizzle-orm";

const SEED_QUESTIONS = [
  { moduleId: 1, category: "Maklerrecht", difficulty: "easy" as const, questionText: "Was ist der Hauptzweck des Maklervertrags?", options: JSON.stringify(["Der Makler kauft die Immobilie","Der Makler erbringt den Nachweis oder die Vermittlung eines Vertrages","Der Makler garantiert den Verkaufserfolg","Der Makler wird Eigentuemer"]), correctAnswer: "1", explanation: "Paragraph 652 BGB: Nachweis oder Vermittlung." },
  { moduleId: 1, category: "Grundlagen", difficulty: "easy" as const, questionText: "Was versteht man unter dem Begriff Immobilie?", options: JSON.stringify(["Nur Grundstuecke","Unbewegliche Sachen insbesondere Grundstuecke und Gebaeude","Nur Wohngebaeude","Nur Gewerbeimmobilien"]), correctAnswer: "1", explanation: "Paragraph 94 BGB: Immobilien sind unbewegliche Sachen." },
  { moduleId: 1, category: "Maklerrecht", difficulty: "medium" as const, questionText: "Was versteht man unter dem Bestellerprinzip?", options: JSON.stringify(["Mieter zahlt immer","Wer den Makler beauftragt zahlt","Beide zahlen 50 Prozent","Vermieter zahlt nie"]), correctAnswer: "1", explanation: "Paragraph 2 Abs 1a WoVermG: Wer bestellt zahlt." },
  { moduleId: 1, category: "Grundlagen", difficulty: "medium" as const, questionText: "Welche Behoerde erteilt die Maklererlaubnis nach Paragraph 34c GewO?", options: JSON.stringify(["Finanzamt","Gewerbeamt","Grundbuchamt","IHK"]), correctAnswer: "1", explanation: "Das Gewerbeamt der zustaendigen Gemeinde erteilt die Erlaubnis." },
  { moduleId: 1, category: "Grundlagen", difficulty: "hard" as const, questionText: "Was ist ein wesentlicher Bestandteil eines Grundstuecks nach Paragraph 94 BGB?", options: JSON.stringify(["Alle beweglichen Sachen","Fest mit dem Boden verbundene Sachen insbesondere Gebaeude","Nur das Gebaeude","Alle Gegenstaende im Gebaeude"]), correctAnswer: "1", explanation: "Paragraph 94 BGB: Wesentliche Bestandteile sind fest verbundene Sachen." },
  { moduleId: 2, category: "Paragraph 34c GewO", difficulty: "easy" as const, questionText: "Wer benoetigt eine Erlaubnis nach Paragraph 34c GewO?", options: JSON.stringify(["Nur Wohnimmobilienmakler","Gewerbliche Immobilienmakler Bautraeger und Baubetreuer","Alle Eigentuemer","Nur WEG-Verwalter"]), correctAnswer: "1", explanation: "Paragraph 34c GewO gilt fuer gewerbliche Makler Bautraeger und Baubetreuer." },
  { moduleId: 2, category: "MaBV", difficulty: "medium" as const, questionText: "Was regelt die MaBV hauptsaechlich?", options: JSON.stringify(["Nur Provision","Pflichten bei Vermoegenswerten und Buchfuehrung","Bauvorschriften","Mietpreisbremse"]), correctAnswer: "1", explanation: "Die MaBV regelt Sicherungspflichten und Buchfuehrung fuer Makler." },
  { moduleId: 2, category: "Verbraucherschutz", difficulty: "medium" as const, questionText: "Welches Widerrufsrecht haben Verbraucher bei Fernabsatz-Maklervertraegen?", options: JSON.stringify(["Kein Widerrufsrecht","14 Tage","30 Tage","Nur ueber 500 Euro"]), correctAnswer: "1", explanation: "Paragraph 312g BGB: 14 Tage Widerrufsrecht bei Fernabsatz." },
  { moduleId: 3, category: "WEG-Recht", difficulty: "easy" as const, questionText: "Was ist eine Eigentueemerversammlung nach WEG?", options: JSON.stringify(["Freiwilliges Mietertreffen","Beschlussfassendes Organ der WEG","Treffen nur fuer Verwalter","Pflicht nur bei Sanierungen"]), correctAnswer: "1", explanation: "Paragraph 23 WEG: Die Eigentueemerversammlung ist das hoechste Beschlussorgan." },
  { moduleId: 3, category: "Mietverwaltung", difficulty: "medium" as const, questionText: "Was ist die Hauptpflicht des Vermieters nach BGB?", options: JSON.stringify(["Schoenheitsreparaturen","Mietsache in gebrauchsfaehigem Zustand ueberlassen und erhalten","Nebenkosten zahlen","Verwaltungsgebuehren tragen"]), correctAnswer: "1", explanation: "Paragraph 535 BGB: Vermieter muss Mietsache in vertragsgemaesgem Zustand erhalten." },
  { moduleId: 3, category: "Mietverwaltung", difficulty: "hard" as const, questionText: "Welche Frist gilt fuer die Betriebskostenabrechnung?", options: JSON.stringify(["6 Monate","12 Monate nach Abrechnungszeitraum","24 Monate","Keine Frist"]), correctAnswer: "1", explanation: "Paragraph 556 Abs 3 BGB: 12 Monate nach Ende des Abrechnungszeitraums." },
  { moduleId: 4, category: "Wertermittlung", difficulty: "easy" as const, questionText: "Welche drei Verfahren sind nach ImmoWertV anerkannt?", options: JSON.stringify(["DCF NAV Residualwert","Ertragswert Sachwert Vergleichswertverfahren","Liquidations Substanz Zukunftswert","Marktwert Buchwert Ertragswert"]), correctAnswer: "1", explanation: "ImmoWertV 2021: Vergleichswert- Ertragswert- und Sachwertverfahren." },
  { moduleId: 4, category: "Wertermittlung", difficulty: "medium" as const, questionText: "Wann ist das Ertragswertverfahren besonders geeignet?", options: JSON.stringify(["Eigengenutztes Einfamilienhaus","Renditeobjekte und Gewerbeimmobilien","Unbebaute Grundstuecke","Neubauprojekte"]), correctAnswer: "1", explanation: "Das Ertragswertverfahren ist ideal fuer Renditeobjekte." },
  { moduleId: 4, category: "Gutachten", difficulty: "hard" as const, questionText: "Was ist der Verkehrswert laut Paragraph 194 BauGB?", options: JSON.stringify(["Steuerlicher Einheitswert","Im gewoehnlichen Geschaeftsverkehr erzielbarer Preis","Versicherungswert","Beleihungswert der Bank"]), correctAnswer: "1", explanation: "Paragraph 194 BauGB: Verkehrswert ist der im gewoehnlichen Geschaeftsverkehr erzielbare Preis." },
  { moduleId: 5, category: "Paragraph 34i GewO", difficulty: "easy" as const, questionText: "Wer benoetigt eine Erlaubnis nach Paragraph 34i GewO?", options: JSON.stringify(["Nur Banken","Gewerbliche Immobiliardarlehensvermittler","Alle Kreditberater","Nur Versicherungsmakler"]), correctAnswer: "1", explanation: "Paragraph 34i GewO: Gewerbliche Darlehensvermittler benoetigen Erlaubnis." },
  { moduleId: 5, category: "Finanzierung", difficulty: "medium" as const, questionText: "Was ist der Beleihungswert?", options: JSON.stringify(["Aktueller Marktwert","Nachhaltig erzielbarer Wert als Kreditsicherheit","Kaufpreis minus Eigenkapital","Steuerlicher Einheitswert"]), correctAnswer: "1", explanation: "Beleihungswert ist der dauerhaft erzielbare Wert als Kreditsicherheit." },
  { moduleId: 5, category: "Paragraph 34i GewO", difficulty: "hard" as const, questionText: "Welche Weiterbildungspflicht gilt fuer Paragraph 34i-Erlaubnisinhaber?", options: JSON.stringify(["Keine","20 Stunden pro Jahr","40 Stunden in 2 Jahren","60 Stunden in 3 Jahren"]), correctAnswer: "3", explanation: "60 Weiterbildungsstunden innerhalb von 3 Jahren sind Pflicht." },
];

export async function seedQuizQuestionsIfEmpty(): Promise<void> {
  const db = await getDb();
  if (!db) return;
  try {
    const existing = await db.select({ count: sql<number>`count(*)` }).from(questionBank);
    const count = Number(existing[0]?.count ?? 0);
    if (count > 0) { console.log("[Quiz] Already seeded:", count, "questions"); return; }
    console.log("[Quiz] Seeding", SEED_QUESTIONS.length, "questions...");
    await db.insert(questionBank).values(SEED_QUESTIONS);
    console.log("[Quiz] Seeded successfully");
  } catch (error) { console.error("[Quiz] Seed error:", error); }
}
