-- Batch 5: 50 additional exam questions for Module 5 (§34i Darlehensvermittlung)
-- Total after this batch: 300 questions
-- Distribution: Rechtliche Grundlagen (10), Darlehensarten (10), Finanzierungsplanung (10), Bonitätsprüfung (7), Risiken (7), Verbraucherschutz (6)

INSERT INTO question_bank (moduleId, category, difficulty, questionText, options, correctAnswer, explanation) VALUES

-- Rechtliche Grundlagen (10 Fragen, ID 251-260)
(5, 'Rechtliche Grundlagen', 'easy', 'Was ist ein Grundpfandrecht?', '["Recht an einem Grundstück zur Sicherung einer Forderung", "Recht zum Kauf eines Grundstücks", "Recht zur Nutzung eines Grundstücks", "Recht zur Vermietung eines Grundstücks"]', 'Recht an einem Grundstück zur Sicherung einer Forderung', 'Ein Grundpfandrecht ist ein Recht an einem Grundstück, das zur Sicherung einer Forderung (z.B. Darlehensforderung) dient. Beispiele: Grundschuld, Hypothek.'),

(5, 'Rechtliche Grundlagen', 'medium', 'Welche Rangfolge haben Grundpfandrechte?', '["Nach Eintragungsdatum im Grundbuch (früher = höherer Rang)", "Nach Höhe der Forderung", "Nach Art des Gläubigers", "Alle gleich"]', 'Nach Eintragungsdatum im Grundbuch (früher = höherer Rang)', 'Die Rangfolge von Grundpfandrechten richtet sich nach dem Eintragungsdatum im Grundbuch. Das früher eingetragene Recht hat den höheren Rang und wird bei Verwertung zuerst befriedigt.'),

(5, 'Rechtliche Grundlagen', 'hard', 'Was ist eine Rangänderung?', '["Änderung der Reihenfolge von Grundpfandrechten mit Zustimmung aller Beteiligten", "Änderung der Höhe einer Grundschuld", "Änderung des Gläubigers", "Änderung des Grundstücks"]', 'Änderung der Reihenfolge von Grundpfandrechten mit Zustimmung aller Beteiligten', 'Eine Rangänderung ist die Änderung der Reihenfolge von Grundpfandrechten im Grundbuch. Sie erfordert die Zustimmung aller betroffenen Gläubiger.'),

(5, 'Rechtliche Grundlagen', 'easy', 'Was ist eine Zwangsversteigerung?', '["Gerichtliche Verwertung einer Immobilie zur Befriedigung von Gläubigern", "Freiwilliger Verkauf einer Immobilie", "Vermietung einer Immobilie", "Schenkung einer Immobilie"]', 'Gerichtliche Verwertung einer Immobilie zur Befriedigung von Gläubigern', 'Eine Zwangsversteigerung ist die gerichtliche Verwertung einer Immobilie, um die Forderungen von Gläubigern zu befriedigen, wenn der Schuldner nicht zahlt.'),

(5, 'Rechtliche Grundlagen', 'medium', 'Welche Voraussetzungen müssen für eine Zwangsversteigerung erfüllt sein?', '["Vollstreckbarer Titel, Grundpfandrecht, Zahlungsverzug", "Nur Zahlungsverzug", "Nur Grundpfandrecht", "Nur vollstreckbarer Titel"]', 'Vollstreckbarer Titel, Grundpfandrecht, Zahlungsverzug', 'Für eine Zwangsversteigerung sind erforderlich: ein vollstreckbarer Titel (z.B. Urteil), ein Grundpfandrecht (Grundschuld/Hypothek) und Zahlungsverzug des Schuldners.'),

(5, 'Rechtliche Grundlagen', 'hard', 'Was ist ein Verkehrswertgutachten?', '["Gutachten über den Marktwert einer Immobilie", "Gutachten über den Zustand einer Immobilie", "Gutachten über die Lage einer Immobilie", "Gutachten über die Nutzung einer Immobilie"]', 'Gutachten über den Marktwert einer Immobilie', 'Ein Verkehrswertgutachten ist ein Gutachten über den Marktwert (Verkehrswert) einer Immobilie, erstellt von einem Sachverständigen nach § 194 BauGB.'),

(5, 'Rechtliche Grundlagen', 'easy', 'Was ist eine Teilungserklärung?', '["Erklärung zur Aufteilung eines Gebäudes in Wohnungseigentum", "Erklärung zur Teilung eines Grundstücks", "Erklärung zur Teilung eines Darlehens", "Erklärung zur Teilung einer Erbschaft"]', 'Erklärung zur Aufteilung eines Gebäudes in Wohnungseigentum', 'Eine Teilungserklärung ist eine notarielle Erklärung des Eigentümers, durch die ein Gebäude in Wohnungseigentum aufgeteilt wird (§ 8 WEG).'),

(5, 'Rechtliche Grundlagen', 'medium', 'Was ist eine Auflassungsvormerkung?', '["Sicherung des Anspruchs auf Eigentumsübertragung im Grundbuch", "Sicherung des Anspruchs auf Zahlung", "Sicherung des Anspruchs auf Nutzung", "Sicherung des Anspruchs auf Vermietung"]', 'Sicherung des Anspruchs auf Eigentumsübertragung im Grundbuch', 'Eine Auflassungsvormerkung sichert den Anspruch des Käufers auf Eigentumsübertragung im Grundbuch und schützt ihn vor Verfügungen des Verkäufers (§ 883 BGB).'),

(5, 'Rechtliche Grundlagen', 'hard', 'Was ist eine Reallast?', '["Wiederkehrende Leistung aus einem Grundstück (z.B. Wohnrecht, Nießbrauch)", "Einmalige Zahlung", "Grundschuld", "Hypothek"]', 'Wiederkehrende Leistung aus einem Grundstück (z.B. Wohnrecht, Nießbrauch)', 'Eine Reallast ist eine wiederkehrende Leistung, die aus einem Grundstück zu erbringen ist (z.B. Wohnrecht, Nießbrauch, Altenteil), eingetragen in Abteilung II des Grundbuchs (§ 1105 BGB).'),

(5, 'Rechtliche Grundlagen', 'easy', 'Was ist ein Nießbrauch?', '["Recht zur Nutzung und zum Fruchtgenuss einer Sache", "Recht zum Verkauf einer Sache", "Recht zur Zerstörung einer Sache", "Recht zur Schenkung einer Sache"]', 'Recht zur Nutzung und zum Fruchtgenuss einer Sache', 'Ein Nießbrauch ist das Recht, eine fremde Sache zu nutzen und die Früchte (z.B. Mieteinnahmen) zu ziehen, ohne Eigentümer zu sein (§ 1030 BGB).'),

-- Darlehensarten (10 Fragen, ID 261-270)
(5, 'Darlehensarten', 'easy', 'Was ist ein Volltilgerdarlehen?', '["Darlehen, das am Ende der Zinsbindung vollständig getilgt ist", "Darlehen ohne Tilgung", "Darlehen mit variabler Tilgung", "Darlehen mit Sondertilgung"]', 'Darlehen, das am Ende der Zinsbindung vollständig getilgt ist', 'Ein Volltilgerdarlehen ist ein Darlehen, bei dem die Tilgung so hoch ist, dass die Restschuld am Ende der Zinsbindung null ist (vollständige Tilgung).'),

(5, 'Darlehensarten', 'medium', 'Ein Kunde möchte ein Volltilgerdarlehen über 200.000 EUR mit 10 Jahren Zinsbindung. Wie hoch ist die Tilgung bei 3% Zinsen?', '["Ca. 7,7% (monatliche Rate ca. 1.790 EUR)", "Ca. 5% (monatliche Rate ca. 1.333 EUR)", "Ca. 10% (monatliche Rate ca. 2.167 EUR)", "Ca. 3% (monatliche Rate ca. 1.000 EUR)"]', 'Ca. 7,7% (monatliche Rate ca. 1.790 EUR)', 'Für ein Volltilgerdarlehen über 200.000 EUR mit 10 Jahren Zinsbindung und 3% Zinsen beträgt die Tilgung ca. 7,7%, die monatliche Rate ca. 1.790 EUR (Berechnung mit Annuitätenformel).'),

(5, 'Darlehensarten', 'hard', 'Was ist der Unterschied zwischen Volltilgerdarlehen und normalem Annuitätendarlehen?', '["Volltilgerdarlehen: Restschuld = 0 am Ende, normales Annuitätendarlehen: Restschuld > 0", "Volltilgerdarlehen: variable Tilgung, normales Annuitätendarlehen: feste Tilgung", "Kein Unterschied", "Volltilgerdarlehen: keine Zinsen"]', 'Volltilgerdarlehen: Restschuld = 0 am Ende, normales Annuitätendarlehen: Restschuld > 0', 'Der Unterschied: Bei einem Volltilgerdarlehen ist die Restschuld am Ende der Zinsbindung null, bei einem normalen Annuitätendarlehen bleibt eine Restschuld übrig.'),

(5, 'Darlehensarten', 'easy', 'Was ist ein Cap-Darlehen?', '["Variables Darlehen mit Zinsobergrenze (Cap)", "Darlehen mit festem Zinssatz", "Darlehen ohne Zinsen", "Darlehen mit Sondertilgung"]', 'Variables Darlehen mit Zinsobergrenze (Cap)', 'Ein Cap-Darlehen ist ein variables Darlehen, bei dem der Zinssatz schwankt, aber eine Obergrenze (Cap) nicht überschreiten kann.'),

(5, 'Darlehensarten', 'medium', 'Ein Kunde hat ein Cap-Darlehen mit 3% Cap. Der Marktzins steigt auf 4%. Welcher Zinssatz gilt?', '["3% (Cap greift)", "4% (Marktzins)", "3,5% (Durchschnitt)", "0% (keine Zinsen)"]', '3% (Cap greift)', 'Bei einem Cap-Darlehen mit 3% Cap gilt maximal 3%, auch wenn der Marktzins auf 4% steigt. Der Cap schützt vor steigenden Zinsen.'),

(5, 'Darlehensarten', 'hard', 'Was ist ein Floor bei einem Cap-Darlehen?', '["Zinsuntergrenze (Mindestzins)", "Zinsobergrenze", "Tilgungsrate", "Sondertilgung"]', 'Zinsuntergrenze (Mindestzins)', 'Ein Floor ist eine Zinsuntergrenze bei einem Cap-Darlehen. Der Zinssatz kann nicht unter den Floor sinken, auch wenn der Marktzins niedriger ist.'),

(5, 'Darlehensarten', 'easy', 'Was ist ein Konstantdarlehen?', '["Darlehen mit gleichbleibender monatlicher Rate (Annuität)", "Darlehen mit variabler Rate", "Darlehen ohne Tilgung", "Darlehen mit Sondertilgung"]', 'Darlehen mit gleichbleibender monatlicher Rate (Annuität)', 'Ein Konstantdarlehen ist ein Darlehen mit gleichbleibender monatlicher Rate (Annuität), bestehend aus Zins und Tilgung. Synonym für Annuitätendarlehen.'),

(5, 'Darlehensarten', 'medium', 'Ein Kunde hat ein Konstantdarlehen mit 1.000 EUR monatlicher Rate. Wie verändert sich die Rate bei Zinsänderung?', '["Rate bleibt gleich, Tilgungsanteil ändert sich", "Rate steigt", "Rate sinkt", "Rate und Tilgung bleiben gleich"]', 'Rate bleibt gleich, Tilgungsanteil ändert sich', 'Bei einem Konstantdarlehen bleibt die monatliche Rate gleich. Bei Zinsänderung ändert sich nur der Tilgungsanteil (höhere Zinsen = niedrigere Tilgung, niedrigere Zinsen = höhere Tilgung).'),

(5, 'Darlehensarten', 'hard', 'Was ist ein Disagio?', '["Abschlag vom Darlehensbetrag (Damnum), der als Zinsvorauszahlung dient", "Aufschlag auf den Darlehensbetrag", "Sondertilgung", "Vorfälligkeitsentschädigung"]', 'Abschlag vom Darlehensbetrag (Damnum), der als Zinsvorauszahlung dient', 'Ein Disagio (Damnum) ist ein Abschlag vom Darlehensbetrag, der als Zinsvorauszahlung dient. Beispiel: 5% Disagio bei 100.000 EUR = 95.000 EUR Auszahlung, 100.000 EUR Rückzahlung.'),

(5, 'Darlehensarten', 'easy', 'Welcher Vorteil hat ein Disagio?', '["Niedrigerer Nominalzins, steuerliche Vorteile bei vermieteten Immobilien", "Höherer Nominalzins", "Keine Tilgung", "Sondertilgung möglich"]', 'Niedrigerer Nominalzins, steuerliche Vorteile bei vermieteten Immobilien', 'Ein Disagio führt zu einem niedrigeren Nominalzins und bietet steuerliche Vorteile bei vermieteten Immobilien (Disagio als Werbungskosten absetzbar).'),

-- Finanzierungsplanung (10 Fragen, ID 271-280)
(5, 'Finanzierungsplanung', 'easy', 'Was sind Erwerbsnebenkosten?', '["Kosten neben dem Kaufpreis (Grunderwerbsteuer, Notar, Makler)", "Kosten für Renovierung", "Kosten für Möbel", "Kosten für Umzug"]', 'Kosten neben dem Kaufpreis (Grunderwerbsteuer, Notar, Makler)', 'Erwerbsnebenkosten sind Kosten neben dem Kaufpreis: Grunderwerbsteuer (3,5-6,5%), Notar- und Grundbuchkosten (ca. 1,5-2%), Maklercourtage (0-7,14%).'),

(5, 'Finanzierungsplanung', 'medium', 'Ein Kunde kauft eine Immobilie für 300.000 EUR in Berlin. Wie hoch sind die Erwerbsnebenkosten?', '["Ca. 42.000 EUR (14%)", "Ca. 30.000 EUR (10%)", "Ca. 60.000 EUR (20%)", "Ca. 15.000 EUR (5%)"]', 'Ca. 42.000 EUR (14%)', 'Erwerbsnebenkosten in Berlin: 6% Grunderwerbsteuer + 2% Notar + 7,14% Makler = ca. 15,14% = ca. 45.420 EUR. Ohne Makler ca. 8% = 24.000 EUR.'),

(5, 'Finanzierungsplanung', 'hard', 'Was ist eine 110%-Finanzierung?', '["Finanzierung von Kaufpreis + Erwerbsnebenkosten ohne Eigenkapital", "Finanzierung von 110% des Kaufpreises", "Finanzierung mit 110% Eigenkapital", "Finanzierung mit 110% Zinsen"]', 'Finanzierung von Kaufpreis + Erwerbsnebenkosten ohne Eigenkapital', 'Eine 110%-Finanzierung ist eine Finanzierung von Kaufpreis + Erwerbsnebenkosten ohne Eigenkapital (Vollfinanzierung). Höheres Risiko, höhere Zinsen.'),

(5, 'Finanzierungsplanung', 'easy', 'Was ist eine Anschlussfinanzierung?', '["Finanzierung nach Ablauf der Zinsbindung für die Restschuld", "Erste Finanzierung", "Finanzierung für Renovierung", "Finanzierung für Möbel"]', 'Finanzierung nach Ablauf der Zinsbindung für die Restschuld', 'Eine Anschlussfinanzierung ist eine Finanzierung für die Restschuld nach Ablauf der Zinsbindung des ersten Darlehens.'),

(5, 'Finanzierungsplanung', 'medium', 'Welche Optionen hat ein Kunde für die Anschlussfinanzierung?', '["Prolongation (bei gleicher Bank), Umschuldung (zu anderer Bank), Forward-Darlehen", "Nur Prolongation", "Nur Umschuldung", "Nur Forward-Darlehen"]', 'Prolongation (bei gleicher Bank), Umschuldung (zu anderer Bank), Forward-Darlehen', 'Für die Anschlussfinanzierung gibt es drei Optionen: Prolongation (Verlängerung bei gleicher Bank), Umschuldung (Wechsel zu anderer Bank), Forward-Darlehen (frühzeitige Zinssicherung).'),

(5, 'Finanzierungsplanung', 'hard', 'Was ist ein Forward-Darlehen?', '["Darlehen mit Zinssicherung bis zu 5 Jahre vor Ablauf der Zinsbindung", "Darlehen mit sofortiger Auszahlung", "Darlehen ohne Zinsen", "Darlehen mit variabler Tilgung"]', 'Darlehen mit Zinssicherung bis zu 5 Jahre vor Ablauf der Zinsbindung', 'Ein Forward-Darlehen ist ein Darlehen, bei dem der Zinssatz bis zu 5 Jahre vor Ablauf der Zinsbindung gesichert wird. Aufschlag: ca. 0,01-0,03% pro Monat Forward-Periode.'),

(5, 'Finanzierungsplanung', 'easy', 'Was ist eine Umschuldung?', '["Wechsel zu einer anderen Bank für die Anschlussfinanzierung", "Wechsel des Darlehensbetrags", "Wechsel der Tilgung", "Wechsel der Immobilie"]', 'Wechsel zu einer anderen Bank für die Anschlussfinanzierung', 'Eine Umschuldung ist der Wechsel zu einer anderen Bank für die Anschlussfinanzierung, um bessere Konditionen (niedrigere Zinsen) zu erhalten.'),

(5, 'Finanzierungsplanung', 'medium', 'Ein Kunde hat eine Restschuld von 150.000 EUR. Die aktuelle Bank bietet 3,5%, eine andere Bank 3%. Wie viel spart er bei 10 Jahren?', '["Ca. 7.500 EUR", "Ca. 15.000 EUR", "Ca. 3.750 EUR", "Ca. 30.000 EUR"]', 'Ca. 7.500 EUR', 'Zinsersparnis: 0,5% von 150.000 EUR = 750 EUR pro Jahr × 10 Jahre = 7.500 EUR (vereinfachte Rechnung ohne Tilgung).'),

(5, 'Finanzierungsplanung', 'hard', 'Was ist eine Prolongation?', '["Verlängerung des Darlehens bei der gleichen Bank nach Ablauf der Zinsbindung", "Wechsel zu einer anderen Bank", "Vorzeitige Rückzahlung", "Sondertilgung"]', 'Verlängerung des Darlehens bei der gleichen Bank nach Ablauf der Zinsbindung', 'Eine Prolongation ist die Verlängerung des Darlehens bei der gleichen Bank nach Ablauf der Zinsbindung. Die Bank unterbreitet ein Prolongationsangebot ca. 3 Monate vor Ablauf.'),

(5, 'Finanzierungsplanung', 'easy', 'Welche Frist gilt für die Kündigung eines Darlehens nach § 489 BGB?', '["6 Monate Kündigungsfrist nach 10 Jahren Zinsbindung", "3 Monate", "12 Monate", "1 Monat"]', '6 Monate Kündigungsfrist nach 10 Jahren Zinsbindung', 'Nach § 489 BGB kann ein Darlehen nach 10 Jahren Zinsbindung mit 6 Monaten Kündigungsfrist gekündigt werden, unabhängig von der vereinbarten Zinsbindung.'),

-- Bonitätsprüfung (7 Fragen, ID 281-287)
(5, 'Bonitätsprüfung', 'easy', 'Was ist ein Schufa-Score?', '["Punktzahl zur Bewertung der Kreditwürdigkeit (0-100%)", "Darlehensbetrag", "Zinssatz", "Tilgungsrate"]', 'Punktzahl zur Bewertung der Kreditwürdigkeit (0-100%)', 'Der Schufa-Score ist eine Punktzahl (0-100%), die die Kreditwürdigkeit bewertet. Je höher der Score, desto besser die Bonität.'),

(5, 'Bonitätsprüfung', 'medium', 'Ein Kunde hat einen Schufa-Score von 95%. Wie wird die Bonität bewertet?', '["Sehr gut, niedriges Ausfallrisiko, beste Konditionen", "Schlecht, hohes Ausfallrisiko", "Mittel, durchschnittliches Risiko", "Keine Bewertung"]', 'Sehr gut, niedriges Ausfallrisiko, beste Konditionen', 'Ein Schufa-Score von 95% bedeutet sehr gute Bonität, niedriges Ausfallrisiko und beste Konditionen (niedrigste Zinsen).'),

(5, 'Bonitätsprüfung', 'hard', 'Was ist ein Basisscore bei der Schufa?', '["Allgemeiner Score für alle Branchen (0-100%)", "Branchenspezifischer Score", "Score nur für Banken", "Score nur für Versicherungen"]', 'Allgemeiner Score für alle Branchen (0-100%)', 'Der Basisscore ist ein allgemeiner Score für alle Branchen (0-100%), der die Kreditwürdigkeit unabhängig von der Branche bewertet.'),

(5, 'Bonitätsprüfung', 'easy', 'Welche Faktoren beeinflussen den Schufa-Score negativ?', '["Zahlungsverzug, Mahnungen, Insolvenzen, viele Kreditanfragen", "Pünktliche Zahlungen", "Hohes Einkommen", "Viel Eigenkapital"]', 'Zahlungsverzug, Mahnungen, Insolvenzen, viele Kreditanfragen', 'Negative Faktoren für den Schufa-Score: Zahlungsverzug, Mahnungen, Insolvenzen, Pfändungen, viele Kreditanfragen in kurzer Zeit.'),

(5, 'Bonitätsprüfung', 'medium', 'Ein Kunde hat 5 Kreditanfragen in 2 Wochen gestellt. Welche Auswirkung hat das auf den Schufa-Score?', '["Negativer Einfluss, Score sinkt", "Positiver Einfluss, Score steigt", "Keine Auswirkung", "Score verdoppelt sich"]', 'Negativer Einfluss, Score sinkt', 'Viele Kreditanfragen in kurzer Zeit wirken sich negativ auf den Schufa-Score aus, da sie auf finanzielle Schwierigkeiten hindeuten können.'),

(5, 'Bonitätsprüfung', 'hard', 'Was ist der Unterschied zwischen Konditionsanfrage und Kreditanfrage bei der Schufa?', '["Konditionsanfrage: keine Auswirkung auf Score, Kreditanfrage: negative Auswirkung", "Konditionsanfrage: negative Auswirkung, Kreditanfrage: keine Auswirkung", "Kein Unterschied", "Beide positiv"]', 'Konditionsanfrage: keine Auswirkung auf Score, Kreditanfrage: negative Auswirkung', 'Konditionsanfrage (KK-Anfrage): keine Auswirkung auf Score, nur für den anfragenden Kreditgeber sichtbar. Kreditanfrage (AK-Anfrage): negative Auswirkung, für alle Kreditgeber sichtbar.'),

(5, 'Bonitätsprüfung', 'easy', 'Wie lange werden negative Schufa-Einträge gespeichert?', '["3 Jahre nach Erledigung", "1 Jahr", "5 Jahre", "10 Jahre"]', '3 Jahre nach Erledigung', 'Negative Schufa-Einträge (z.B. Mahnungen, Insolvenzen) werden 3 Jahre nach Erledigung gelöscht.'),

-- Risiken (7 Fragen, ID 288-294)
(5, 'Risiken', 'easy', 'Was ist ein Zinsänderungsrisiko?', '["Risiko steigender Zinsen bei Anschlussfinanzierung", "Risiko sinkender Immobilienpreise", "Risiko sinkender Einkommen", "Risiko steigender Nebenkosten"]', 'Risiko steigender Zinsen bei Anschlussfinanzierung', 'Das Zinsänderungsrisiko ist das Risiko, dass die Zinsen bei der Anschlussfinanzierung höher sind als bei der Erstfinanzierung, was zu höheren Raten führt.'),

(5, 'Risiken', 'medium', 'Ein Kunde hat eine Restschuld von 200.000 EUR. Die Zinsen steigen von 2% auf 4%. Wie viel höher ist die monatliche Rate?', '["Ca. 333 EUR höher", "Ca. 167 EUR höher", "Ca. 500 EUR höher", "Keine Änderung"]', 'Ca. 333 EUR höher', 'Zinsänderung: 2% von 200.000 EUR = 4.000 EUR pro Jahr = 333 EUR pro Monat höhere Zinslast (vereinfachte Rechnung ohne Tilgung).'),

(5, 'Risiken', 'hard', 'Wie kann ein Kunde das Zinsänderungsrisiko absichern?', '["Forward-Darlehen, lange Zinsbindung, Sondertilgungen", "Nur Forward-Darlehen", "Nur lange Zinsbindung", "Nur Sondertilgungen"]', 'Forward-Darlehen, lange Zinsbindung, Sondertilgungen', 'Absicherung gegen Zinsänderungsrisiko: Forward-Darlehen (frühzeitige Zinssicherung), lange Zinsbindung (15-20 Jahre), Sondertilgungen (Restschuld reduzieren).'),

(5, 'Risiken', 'easy', 'Was ist ein Immobilienwertrisiko?', '["Risiko sinkender Immobilienpreise", "Risiko steigender Zinsen", "Risiko sinkender Einkommen", "Risiko steigender Nebenkosten"]', 'Risiko sinkender Immobilienpreise', 'Das Immobilienwertrisiko ist das Risiko, dass der Wert der Immobilie sinkt und bei Verkauf oder Zwangsversteigerung nicht ausreicht, um die Restschuld zu tilgen.'),

(5, 'Risiken', 'medium', 'Ein Kunde kauft eine Immobilie für 300.000 EUR mit 10% Eigenkapital. Der Immobilienwert sinkt auf 250.000 EUR. Wie hoch ist der Verlust?', '["80.000 EUR (Eigenkapital + Wertverlust)", "50.000 EUR (nur Wertverlust)", "30.000 EUR (nur Eigenkapital)", "Kein Verlust"]', '80.000 EUR (Eigenkapital + Wertverlust)', 'Verlust: 30.000 EUR Eigenkapital + 50.000 EUR Wertverlust = 80.000 EUR. Die Restschuld (270.000 EUR) ist höher als der Immobilienwert (250.000 EUR).'),

(5, 'Risiken', 'hard', 'Was ist ein Klumpenrisiko?', '["Konzentration des Vermögens in einer Immobilie", "Risiko steigender Zinsen", "Risiko sinkender Einkommen", "Risiko steigender Nebenkosten"]', 'Konzentration des Vermögens in einer Immobilie', 'Das Klumpenrisiko ist das Risiko, dass das gesamte Vermögen in einer Immobilie konzentriert ist und keine Diversifikation besteht.'),

(5, 'Risiken', 'easy', 'Was ist eine Risikolebensversicherung?', '["Versicherung, die im Todesfall die Restschuld tilgt", "Versicherung gegen Arbeitslosigkeit", "Versicherung gegen Krankheit", "Versicherung gegen Zinsänderungen"]', 'Versicherung, die im Todesfall die Restschuld tilgt', 'Eine Risikolebensversicherung zahlt im Todesfall des Versicherten die Versicherungssumme (z.B. Restschuld des Darlehens) an die Hinterbliebenen.'),

-- Verbraucherschutz (6 Fragen, ID 295-300)
(5, 'Verbraucherschutz', 'easy', 'Was ist ein ESIS-Merkblatt?', '["Europäisches Standardisiertes Merkblatt mit Informationen zum Darlehen", "Schufa-Auskunft", "Widerrufsbelehrung", "Beratungsprotokoll"]', 'Europäisches Standardisiertes Merkblatt mit Informationen zum Darlehen', 'Das ESIS-Merkblatt (European Standardised Information Sheet) ist ein standardisiertes Merkblatt mit Informationen zum Darlehen (Zinssatz, Rate, Kosten, Laufzeit).'),

(5, 'Verbraucherschutz', 'medium', 'Wann muss ein ESIS-Merkblatt ausgehändigt werden?', '["Vor Abschluss des Darlehensvertrags", "Nach Abschluss des Vertrags", "Nur auf Anfrage", "Nie"]', 'Vor Abschluss des Darlehensvertrags', 'Das ESIS-Merkblatt muss dem Kunden vor Abschluss des Darlehensvertrags ausgehändigt werden, damit er die Konditionen vergleichen kann.'),

(5, 'Verbraucherschutz', 'hard', 'Was ist eine Beratungsdokumentation?', '["Protokoll über die Beratung des Kunden mit Empfehlungen und Entscheidungen", "Schufa-Auskunft", "ESIS-Merkblatt", "Widerrufsbelehrung"]', 'Protokoll über die Beratung des Kunden mit Empfehlungen und Entscheidungen', 'Eine Beratungsdokumentation ist ein Protokoll über die Beratung des Kunden, das die besprochenen Themen, Empfehlungen und Entscheidungen festhält (Pflicht nach § 511 BGB).'),

(5, 'Verbraucherschutz', 'easy', 'Welche Informationen muss eine Beratungsdokumentation enthalten?', '["Kundenwünsche, Empfehlungen, Gründe für Empfehlung, Entscheidung", "Nur Kundenwünsche", "Nur Empfehlungen", "Nur Entscheidung"]', 'Kundenwünsche, Empfehlungen, Gründe für Empfehlung, Entscheidung', 'Eine Beratungsdokumentation muss enthalten: Kundenwünsche, Empfehlungen des Beraters, Gründe für die Empfehlung, Entscheidung des Kunden.'),

(5, 'Verbraucherschutz', 'medium', 'Ein Kunde erhält keine Beratungsdokumentation. Welche Rechtsfolge tritt ein?', '["Beweislastumkehr: Bank muss beweisen, dass Beratung korrekt war", "Keine Rechtsfolge", "Vertrag ist nichtig", "Nur Bußgeld"]', 'Beweislastumkehr: Bank muss beweisen, dass Beratung korrekt war', 'Ohne Beratungsdokumentation tritt eine Beweislastumkehr ein: Die Bank muss beweisen, dass die Beratung korrekt war, nicht der Kunde.'),

(5, 'Verbraucherschutz', 'hard', 'Was ist eine Aufklärungspflicht des Darlehensvermittlers?', '["Pflicht, den Kunden über Risiken, Kosten und Alternativen aufzuklären", "Pflicht, nur über Vorteile zu informieren", "Pflicht, nur über Kosten zu informieren", "Keine Pflicht"]', 'Pflicht, den Kunden über Risiken, Kosten und Alternativen aufzuklären', 'Die Aufklärungspflicht ist die Pflicht des Darlehensvermittlers, den Kunden umfassend über Risiken, Kosten, Alternativen und Konsequenzen aufzuklären.');
